version: 2

jobs:
  build:
    working_directory: ~/mysql_point
    docker:
      - image: circleci/ruby:2.3
        environment:
          DATABASE_URL: mysql2://root@127.0.0.1/circle_test
      - image: circleci/mysql:5.7

    steps:
      - checkout
      - run: bin/setup
      - run: appraisal install
      - run: appraisal rake test
